USE [master]
GO

/****** Object:  Database [BD_MIGHTVR]    Script Date: 20/02/2025 10:54:05 ******/
CREATE DATABASE [BD_MIGHTVR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_MIGHTVR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_MIGHTVR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BD_MIGHTVR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BD_MIGHTVR_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_MIGHTVR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_MIGHTVR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_MIGHTVR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_MIGHTVR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_MIGHTVR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_MIGHTVR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BD_MIGHTVR] SET  MULTI_USER 
GO

ALTER DATABASE [BD_MIGHTVR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_MIGHTVR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_MIGHTVR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_MIGHTVR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BD_MIGHTVR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_MIGHTVR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BD_MIGHTVR] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BD_MIGHTVR] SET  READ_WRITE 
GO

